apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bezzbot-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bezzbot-app
    spec:
      containers:
      - name: bezzbot-app
        image: webapp:1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 80
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: bezbot-service
#  labels:
#    app: bezbot-service
#spec:
#  type: NodePort
#  ports:
    # the port that this service should serve on
#    - port: 80
  # label keys and values that must match in order to receive traffic for this service
#  selector:
#    app: bezzbot-app
