apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bizzbot-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bizzbot-app
    spec:
      containers:
      - name: bizzbot-app
        image: webapp:1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 80
---
#apiVersion: v1
#kind: Service
#metadata:
 # name: chatter-service
  #labels:
   # app: chatter-service
#spec:
 # type: NodePort
  #ports:
    # the port that this service should serve on
   # - port: 80
  # label keys and values that must match in order to receive traffic for this service
  #selector:
   # app: microservice-chatter
